### ISSUE TITLE
Ajout / suppression automatique du rôle premium 

### ISSUE THREAD

**Issue by Unaty498** [Hogwarts-Adventure/Hagrid#1]
Id du rôle : 695349314645524600

Dans l'event message (filtrer avec l'id de la guilde : 688068666889207820)

Si possède role et pas premium => lui enlever

Si ne possède pas role et premium => lui ajouter

**Comment by Lukaribou** [comment]
``users.premium`` c'est un timestamp, donc si la date est passée je le mets à 0 ?

**Comment by Lukaribou** [comment]
``users.premium`` = temps restant de premium en tout
``users.datePremium`` = date jusqu'à laquelle le premium est activé
